# Generated by Django 2.0.7 on 2021-11-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='Some product'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.TextField(default='112358'),
        ),
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.TextField(default='Product'),
        ),
    ]
